---
- name: Setup new sudo user if not exists
  hosts: workers
  gather_facts: no 
  roles:
    - role: security_access_bootstrap
      vars:
        ansible_user: root
  
- name: Install docker
  hosts: workers
  become: yes
  roles:
    - docker_install